platform :ios, '15.0'
use_frameworks!

target 'MediaFlow' do
  # Usamos ffmpeg-kit-ios-min para un binario optimizado con los codecs comunes
  # (mp3, aac, flac, wav, ogg, mp4, h264, webm, vp8, vp9, jpeg, png, etc.)
  pod 'ffmpeg-kit-ios-min', '~> 6.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
